In [10]:
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('uber_fares.csv')
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   key                200000 non-null  int64
 1   date               200000 non-null  str
 2   fare_amount        200000 non-null  float64
 3   pickup_datetime    200000 non-null  str
 4   pickup_longitude   200000 non-null  float64
 5   pickup_latitude    200000 non-null  float64
 6   dropoff_longitude  199999 non-null  float64
 7   dropoff_latitude   199999 non-null  float64
 8   passenger_count    200000 non-null  int64
dtypes: float64(5), int64(2), str(2)
memory usage: 13.7 MB

In [5]:
data.head()

,key,date,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,24238194,2015-05-07 19:50:00,8.47,2015-05-07 19:50:00 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,27835199,2009-07-17 20:00:04,7.60,2009-07-17 20:00:04 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,44984355,2009-08-24 21:49:07,12.65,2009-08-24 21:49:07 UTC,-74.005043,40.740770,-73.962565,40.772647,1
3,25894730,2009-06-26 08:17:45,5.01,2009-06-26 08:17:45 UTC,-73.976124,40.790844,-73.965316,40.803349,3
4,17610152,2014-08-28 17:46:18,15.64,2014-08-28 17:46:18 UTC,-73.925023,40.744085,-73.973082,40.761247,5

In [6]:
null_rows = data[data.isnull().any(axis=1)]
print(f"Number of rows with null values: {len(null_rows)}")
display(null_rows)

Number of rows with null values: 1

,key,date,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
87946,32736015,2013-07-02 03:53:05,24.15,2013-07-02 03:53:05 UTC,-73.950581,40.779692,NaN,NaN,0

In [7]:
impossible_passenger = data[data['passenger_count'] <= 0]
print(f"Number of impossible passenger counts (less than or equal to 0): {len(impossible_passenger)}")
display(impossible_passenger)

Number of impossible passenger counts (less than or equal to 0): 709

,key,date,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
333,2137942,2011-08-05 07:07:59,9.46,2011-08-05 07:07:59 UTC,-74.013900,40.707800,-73.992300,40.749300,0
908,8484351,2011-09-06 12:20:35,12.42,2011-09-06 12:20:35 UTC,-73.981000,40.764600,-73.962900,40.778400,0
926,32941306,2012-03-26 18:10:36,3.21,2012-03-26 18:10:36 UTC,-73.979978,40.765821,-73.983894,40.766873,0
2000,12591041,2012-04-20 15:12:09,14.61,2012-04-20 15:12:09 UTC,-73.975285,40.750138,-73.974729,40.783151,0
3011,39400625,2012-01-07 19:23:12,7.65,2012-01-07 19:23:12 UTC,-73.977900,40.789100,-73.983700,40.773600,0
...,...,...,...,...,...,...,...,...,...
196797,26965490,2011-01-17 15:48:16,3.30,2011-01-17 15:48:16 UTC,-74.000760,40.757637,-74.004852,40.751947,0
197103,49116579,2011-12-10 15:35:54,6.24,2011-12-10 15:35:54 UTC,0.000000,0.000000,0.000000,0.000000,0
198872,12988511,2011-09-20 19:55:00,6.02,2011-09-20 19:55:00 UTC,-73.980300,40.742800,-73.967900,40.755600,0
198902,54393172,2011-08-22 21:06:14,11.06,2011-08-22 21:06:14 UTC,-73.996700,40.737200,-74.008500,40.704000,0
198953,47743848,2012-04-13 08:25:55,4.79,2012-04-13 08:25:55 UTC,-73.844310,40.721270,-73.842987,40.713435,0

In [8]:
impossible_longitude = data[data['pickup_longitude'] == 0]
print(f"Number of impossible longitude counts (less than or equal to 0): {len(impossible_longitude)}")
display(impossible_longitude)

Number of impossible longitude counts (less than or equal to 0): 3786

,key,date,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
7,44195482,2012-12-11 13:53:11,2.70,2012-12-11 13:53:11 UTC,0.0,0.0,0.0,0.0,1
11,6379048,2011-05-23 22:15:36,7.84,2011-05-23 22:15:36 UTC,0.0,0.0,0.0,0.0,1
65,21993993,2014-05-05 19:22:23,6.77,2014-05-05 19:22:23 UTC,0.0,0.0,0.0,0.0,1
92,1454546,2011-12-02 14:08:42,6.29,2011-12-02 14:08:42 UTC,0.0,0.0,0.0,0.0,1
120,17358122,2010-08-20 19:38:44,6.67,2010-08-20 19:38:44 UTC,0.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...
199718,49162936,2011-08-19 07:13:31,5.70,2011-08-19 07:13:31 UTC,0.0,0.0,0.0,0.0,1
199724,46007628,2013-10-11 11:22:03,6.47,2013-10-11 11:22:03 UTC,0.0,0.0,0.0,0.0,1
199880,35013970,2014-02-22 06:49:55,6.66,2014-02-22 06:49:55 UTC,0.0,0.0,0.0,0.0,1
199883,44115598,2012-09-10 17:37:26,12.03,2012-09-10 17:37:26 UTC,0.0,0.0,0.0,0.0,2
199963,50075618,2012-09-22 07:46:47,37.26,2012-09-22 07:46:47 UTC,0.0,0.0,0.0,0.0,1

In [9]:
impossible = data[(data['pickup_longitude'] == data['dropoff_longitude']) & (data['pickup_latitude'] == data['dropoff_latitude'])]
print(f"Number of trips with same pickup and dropoff coordinates: {len(impossible)}")
display(impossible)

Number of trips with same pickup and dropoff coordinates: 5632

,key,date,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
5,44470845,2011-02-12 02:28:47,4.05,2011-02-12 02:28:47 UTC,-73.969019,40.755910,-73.969019,40.755910,1
7,44195482,2012-12-11 13:53:11,2.70,2012-12-11 13:53:11 UTC,0.000000,0.000000,0.000000,0.000000,1
11,6379048,2011-05-23 22:15:36,7.84,2011-05-23 22:15:36 UTC,0.000000,0.000000,0.000000,0.000000,1
48,22405517,2013-01-03 22:26:56,57.74,2013-01-03 22:26:56 UTC,-73.993498,40.764686,-73.993498,40.764686,1
65,21993993,2014-05-05 19:22:23,6.77,2014-05-05 19:22:23 UTC,0.000000,0.000000,0.000000,0.000000,1
...,...,...,...,...,...,...,...,...,...
199880,35013970,2014-02-22 06:49:55,6.66,2014-02-22 06:49:55 UTC,0.000000,0.000000,0.000000,0.000000,1
199883,44115598,2012-09-10 17:37:26,12.03,2012-09-10 17:37:26 UTC,0.000000,0.000000,0.000000,0.000000,2
199917,45368488,2013-06-24 22:13:37,5.04,2013-06-24 22:13:37 UTC,-73.793768,40.656939,-73.793768,40.656939,1
199932,46517645,2011-03-22 13:59:56,25.86,2011-03-22 13:59:56 UTC,-73.974618,40.756295,-73.974618,40.756295,5
199963,50075618,2012-09-22 07:46:47,37.26,2012-09-22 07:46:47 UTC,0.000000,0.000000,0.000000,0.000000,1